name: PopupExample

options:
  developmentLanguage: en
  deploymentTarget:
    iOS: 15.0

packages:
  ComposablePopup:
    path: ../

targets:
  PopupExample:
    type: application
    platform: iOS
    settings:
      INFOPLIST_FILE: Info.plist
      TARGETED_DEVICE_FAMILY: 1
      PRODUCT_BUNDLE_IDENTIFIER: com.dev.PopupExample
      MARKETING_VERSION: 1.0
      CURRENT_PROJECT_VERSION: 1
    sources:
      - PopupExample
    dependencies:
      - package: ComposablePopup

